spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    #server should not register
    register-with-eureka: false
    #prevent fetching its own service list
    fetch-registry: false